### ISSUE TITLE
chat application demo

### ISSUE THREAD

**Issue by ohmydevops** [swooletw/awesome-swoole#9]
i create a chat application with laravel swoole.
I'll be appreciative to you, if this software will be listed in this repo links for people who need a demo  for laravel-swoole.
[link to repo](https://github.com/amirbagh75/real-time-messaging)

----
sorry for my bad english

**Comment by isaachbn** [comment]
@amirbagh75 

You can use this skeleton for any project startup with swoole and laravel.  It is dockerized and with nginx with active secutiry mod.

https://github.com/isaachbn/swoole-nginx-laravel

**Comment by Arkanius** [comment]
Thanks @amirbagh75 ! 

I enjoyed your example! Unfortunately I think this is out of the scope of this repo so I'll close it, but, I think this is a really good example on how use swoole and websockets. I'd appreciate if you could keep this updated with laravel last version, this way all community could enjoy the reference.
